name: Chris Payumo
author:
baseurl:
description: Software Engineer
github: https://github.com/cpayumo
twitter: https://twitter.com/payumochris
facebook: https://www.facebook.com/chris.payumo
linkedin: https://www.linkedin.com/in/cpayumo/
email: cpayumo97@gmail.com
location: Fairfield, cA
disqus:

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown:
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
